Repository Nub-en-Nuber/NuberJam-Android, pull requests merged in 2023-08, with the labels that each got.

#47 feat(account) : MP-239 Add Login Session to Preferences DataStore
  app/src/main/java/com/example/nuberjam/data/Repository.kt
  app/src/main/java/com/example/nuberjam/data/model/Account.kt
  app/src/main/java/com/example/nuberjam/data/model/Album.kt
  app/src/main/java/com/example/nuberjam/data/model/Music.kt
  app/src/main/java/com/example/nuberjam/data/model/Playlist.kt
  app/src/main/java/com/example/nuberjam/data/source/local/service/DbDao.kt
  app/src/main/java/com/example/nuberjam/data/source/preferences/AppPreferences.kt
  app/src/main/java/com/example/nuberjam/data/source/remote/response/DataResponse.kt
  app/src/main/java/com/example/nuberjam/data/source/remote/service/ApiService.kt
  app/src/main/java/com/example/nuberjam/ui/authentication/AuthViewModel.kt
  app/src/main/java/com/example/nuberjam/ui/authentication/LoginFragment.kt
  app/src/main/java/com/example/nuberjam/ui/authentication/RegisterFragment.kt
  app/src/main/java/com/example/nuberjam/ui/main/MainActivity.kt
  app/src/main/java/com/example/nuberjam/ui/main/adapter/AlbumAdapter.kt
  app/src/main/java/com/example/nuberjam/ui/main/adapter/LibraryAdapter.kt
  app/src/main/java/com/example/nuberjam/ui/main/adapter/MusicAdapter.kt
  app/src/main/java/com/example/nuberjam/ui/main/adapter/PlaylistAdapter.kt
  app/src/main/java/com/example/nuberjam/ui/main/home/HomeFragment.kt
  app/src/main/java/com/example/nuberjam/ui/main/home/HomeViewModel.kt
  app/src/main/java/com/example/nuberjam/ui/main/library/LibraryFragment.kt
  app/src/main/java/com/example/nuberjam/ui/main/library/LibraryViewModel.kt
  app/src/main/java/com/example/nuberjam/ui/main/library/detail/DetailLibraryViewModel.kt
  app/src/main/java/com/example/nuberjam/ui/main/music/MusicViewModel.kt
  app/src/main/java/com/example/nuberjam/ui/main/profile/ProfileFragment.kt
  app/src/main/java/com/example/nuberjam/ui/main/profile/ProfileViewModel.kt
  app/src/main/java/com/example/nuberjam/ui/main/search/SearchViewModel.kt
  app/src/main/java/com/example/nuberjam/utils/Event.kt
  app/src/main/java/com/example/nuberjam/utils/Helper.kt
  app/src/main/java/com/example/nuberjam/utils/Mapping.kt
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
Labels: account, feat

#48 feat(account) : MP-225 Login Feature
  app/src/main/java/com/example/nuberjam/data/Repository.kt
  app/src/main/java/com/example/nuberjam/data/model/Account.kt
  app/src/main/java/com/example/nuberjam/data/model/Album.kt
  app/src/main/java/com/example/nuberjam/data/model/Music.kt
  app/src/main/java/com/example/nuberjam/data/model/Playlist.kt
  app/src/main/java/com/example/nuberjam/data/source/local/service/DbDao.kt
  app/src/main/java/com/example/nuberjam/data/source/preferences/AppPreferences.kt
  app/src/main/java/com/example/nuberjam/data/source/remote/response/DataResponse.kt
  app/src/main/java/com/example/nuberjam/data/source/remote/service/ApiService.kt
  app/src/main/java/com/example/nuberjam/ui/ViewModelFactory.kt
  app/src/main/java/com/example/nuberjam/ui/authentication/AuthViewModel.kt
  app/src/main/java/com/example/nuberjam/ui/authentication/LoginFragment.kt
  app/src/main/java/com/example/nuberjam/ui/authentication/RegisterFragment.kt
  app/src/main/java/com/example/nuberjam/ui/main/MainActivity.kt
  app/src/main/java/com/example/nuberjam/ui/main/adapter/AlbumAdapter.kt
  app/src/main/java/com/example/nuberjam/ui/main/adapter/LibraryAdapter.kt
  app/src/main/java/com/example/nuberjam/ui/main/adapter/MusicAdapter.kt
  app/src/main/java/com/example/nuberjam/ui/main/adapter/PlaylistAdapter.kt
  app/src/main/java/com/example/nuberjam/ui/main/home/HomeFragment.kt
  app/src/main/java/com/example/nuberjam/ui/main/home/HomeViewModel.kt
  app/src/main/java/com/example/nuberjam/ui/main/library/LibraryFragment.kt
  app/src/main/java/com/example/nuberjam/ui/main/library/LibraryViewModel.kt
  app/src/main/java/com/example/nuberjam/ui/main/library/detail/DetailLibraryViewModel.kt
  app/src/main/java/com/example/nuberjam/ui/main/music/MusicViewModel.kt
  app/src/main/java/com/example/nuberjam/ui/main/profile/ProfileFragment.kt
  app/src/main/java/com/example/nuberjam/ui/main/profile/ProfileViewModel.kt
  app/src/main/java/com/example/nuberjam/ui/main/search/SearchViewModel.kt
  app/src/main/java/com/example/nuberjam/utils/Event.kt
  app/src/main/java/com/example/nuberjam/utils/Helper.kt
  app/src/main/java/com/example/nuberjam/utils/Mapping.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/linear_loading.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: account, feat

#49 feat(account) : MP-244 Register API Connection
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/nuberjam/data/Repository.kt
  app/src/main/java/com/example/nuberjam/data/model/Account.kt
  app/src/main/java/com/example/nuberjam/data/model/Album.kt
  app/src/main/java/com/example/nuberjam/data/model/Music.kt
  app/src/main/java/com/example/nuberjam/data/model/Playlist.kt
  app/src/main/java/com/example/nuberjam/data/source/local/service/DbDao.kt
  app/src/main/java/com/example/nuberjam/data/source/preferences/AppPreferences.kt
  app/src/main/java/com/example/nuberjam/data/source/remote/response/DataResponse.kt
  app/src/main/java/com/example/nuberjam/data/source/remote/service/ApiService.kt
  app/src/main/java/com/example/nuberjam/ui/ViewModelFactory.kt
  app/src/main/java/com/example/nuberjam/ui/authentication/AuthActivity.kt
  app/src/main/java/com/example/nuberjam/ui/authentication/AuthViewModel.kt
  app/src/main/java/com/example/nuberjam/ui/authentication/LoginFragment.kt
  app/src/main/java/com/example/nuberjam/ui/authentication/RegisterFragment.kt
  app/src/main/java/com/example/nuberjam/ui/main/MainActivity.kt
  app/src/main/java/com/example/nuberjam/ui/main/adapter/AlbumAdapter.kt
  app/src/main/java/com/example/nuberjam/ui/main/adapter/LibraryAdapter.kt
  app/src/main/java/com/example/nuberjam/ui/main/adapter/MusicAdapter.kt
  app/src/main/java/com/example/nuberjam/ui/main/adapter/PlaylistAdapter.kt
  app/src/main/java/com/example/nuberjam/ui/main/home/HomeFragment.kt
  app/src/main/java/com/example/nuberjam/ui/main/home/HomeViewModel.kt
  app/src/main/java/com/example/nuberjam/ui/main/library/LibraryFragment.kt
  app/src/main/java/com/example/nuberjam/ui/main/library/LibraryViewModel.kt
  app/src/main/java/com/example/nuberjam/ui/main/library/detail/DetailLibraryViewModel.kt
  app/src/main/java/com/example/nuberjam/ui/main/music/MusicViewModel.kt
  app/src/main/java/com/example/nuberjam/ui/main/profile/ProfileFragment.kt
  app/src/main/java/com/example/nuberjam/ui/main/profile/ProfileViewModel.kt
  app/src/main/java/com/example/nuberjam/ui/main/search/SearchViewModel.kt
  app/src/main/java/com/example/nuberjam/utils/Constant.kt
  app/src/main/java/com/example/nuberjam/utils/Event.kt
  app/src/main/java/com/example/nuberjam/utils/Helper.kt
  app/src/main/java/com/example/nuberjam/utils/Mapping.kt
  app/src/main/res/layout/activity_auth.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/linear_loading.xml
  app/src/main/res/navigation/auth_navigation.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: account, feat

#50 feat(account) : MP-248 Wiring Register Data to UI
  app/src/main/java/com/example/nuberjam/ui/authentication/AuthViewModel.kt
  app/src/main/java/com/example/nuberjam/ui/authentication/LoginFragment.kt
  app/src/main/java/com/example/nuberjam/ui/authentication/RegisterFragment.kt
  app/src/main/res/layout/fragment_register.xml
  app/src/main/res/layout/password_req_layout.xml
  app/src/main/res/layout/register_appbar.xml
  app/src/main/res/values/strings.xml
Labels: account, feat

#52 feat(account) : MP-249 Form Logic Error
  app/src/main/java/com/example/nuberjam/ui/authentication/AuthViewModel.kt
  app/src/main/java/com/example/nuberjam/ui/authentication/RegisterFragment.kt
  app/src/main/res/values/strings.xml
Labels: account, feat

#53 feat(account) : MP-226 Register Feature
  app/src/main/java/com/example/nuberjam/data/Repository.kt
  app/src/main/java/com/example/nuberjam/data/source/remote/service/ApiService.kt
  app/src/main/java/com/example/nuberjam/ui/authentication/AuthViewModel.kt
  app/src/main/java/com/example/nuberjam/ui/authentication/LoginFragment.kt
  app/src/main/java/com/example/nuberjam/ui/authentication/RegisterFragment.kt
  app/src/main/res/layout/fragment_register.xml
  app/src/main/res/layout/password_req_layout.xml
  app/src/main/res/layout/register_appbar.xml
  app/src/main/res/values/strings.xml
Labels: account, feat

#55 feat(general) : MP-276 Add Animation for Navigation
  app/src/main/res/anim/slide_in_right.xml
  app/src/main/res/anim/slide_out_left.xml
  app/src/main/res/navigation/auth_navigation.xml
  app/src/main/res/navigation/main_navigation.xml
Labels: feat, general

#56 feat(account) : MP-215 Check Login Session
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/nuberjam/data/Repository.kt
  app/src/main/java/com/example/nuberjam/data/model/Account.kt
  app/src/main/java/com/example/nuberjam/data/model/Album.kt
  app/src/main/java/com/example/nuberjam/data/model/Music.kt
  app/src/main/java/com/example/nuberjam/data/model/Playlist.kt
  app/src/main/java/com/example/nuberjam/data/source/local/service/DbDao.kt
  app/src/main/java/com/example/nuberjam/data/source/preferences/AppPreferences.kt
  app/src/main/java/com/example/nuberjam/data/source/remote/response/DataResponse.kt
  app/src/main/java/com/example/nuberjam/data/source/remote/service/ApiConfig.kt
  app/src/main/java/com/example/nuberjam/data/source/remote/service/ApiService.kt
  app/src/main/java/com/example/nuberjam/ui/SplashScreenActivity.kt
  app/src/main/java/com/example/nuberjam/ui/SplashViewModel.kt
  app/src/main/java/com/example/nuberjam/ui/ViewModelFactory.kt
  app/src/main/java/com/example/nuberjam/ui/authentication/AuthActivity.kt
  app/src/main/java/com/example/nuberjam/ui/authentication/AuthViewModel.kt
  app/src/main/java/com/example/nuberjam/ui/authentication/LoginFragment.kt
  app/src/main/java/com/example/nuberjam/ui/authentication/RegisterFragment.kt
  app/src/main/java/com/example/nuberjam/ui/main/MainActivity.kt
  app/src/main/java/com/example/nuberjam/ui/main/adapter/AlbumAdapter.kt
  app/src/main/java/com/example/nuberjam/ui/main/adapter/LibraryAdapter.kt
  app/src/main/java/com/example/nuberjam/ui/main/adapter/MusicAdapter.kt
  app/src/main/java/com/example/nuberjam/ui/main/adapter/PlaylistAdapter.kt
  app/src/main/java/com/example/nuberjam/ui/main/home/HomeFragment.kt
  app/src/main/java/com/example/nuberjam/ui/main/home/HomeViewModel.kt
  app/src/main/java/com/example/nuberjam/ui/main/library/LibraryFragment.kt
  app/src/main/java/com/example/nuberjam/ui/main/library/LibraryViewModel.kt
  app/src/main/java/com/example/nuberjam/ui/main/library/detail/DetailLibraryViewModel.kt
  app/src/main/java/com/example/nuberjam/ui/main/music/MusicViewModel.kt
  app/src/main/java/com/example/nuberjam/ui/main/profile/ProfileFragment.kt
  app/src/main/java/com/example/nuberjam/ui/main/profile/ProfileViewModel.kt
  app/src/main/java/com/example/nuberjam/ui/main/search/SearchViewModel.kt
  app/src/main/java/com/example/nuberjam/utils/Constant.kt
  app/src/main/java/com/example/nuberjam/utils/Event.kt
  app/src/main/java/com/example/nuberjam/utils/FormValidation.kt
  app/src/main/java/com/example/nuberjam/utils/Helper.kt
  app/src/main/java/com/example/nuberjam/utils/Mapping.kt
  app/src/main/res/drawable/ic_navigation_home.xml
  app/src/main/res/drawable/ic_navigation_library.xml
  app/src/main/res/drawable/ic_navigation_profile.xml
  app/src/main/res/layout/activity_auth.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_register.xml
  app/src/main/res/layout/linear_loading.xml
  app/src/main/res/layout/password_req_layout.xml
  app/src/main/res/layout/register_appbar.xml
  app/src/main/res/menu/bottom_navigation_menu.xml
  app/src/main/res/navigation/auth_navigation.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: account, feat

#57 feat(account) : MP-207 APP Splash Screen
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/nuberjam/data/Repository.kt
  app/src/main/java/com/example/nuberjam/data/model/Account.kt
  app/src/main/java/com/example/nuberjam/data/model/Album.kt
  app/src/main/java/com/example/nuberjam/data/model/Music.kt
  app/src/main/java/com/example/nuberjam/data/model/Playlist.kt
  app/src/main/java/com/example/nuberjam/data/source/local/service/DbDao.kt
  app/src/main/java/com/example/nuberjam/data/source/preferences/AppPreferences.kt
  app/src/main/java/com/example/nuberjam/data/source/remote/response/DataResponse.kt
  app/src/main/java/com/example/nuberjam/data/source/remote/service/ApiConfig.kt
  app/src/main/java/com/example/nuberjam/data/source/remote/service/ApiService.kt
  app/src/main/java/com/example/nuberjam/ui/SplashScreenActivity.kt
  app/src/main/java/com/example/nuberjam/ui/SplashViewModel.kt
  app/src/main/java/com/example/nuberjam/ui/ViewModelFactory.kt
  app/src/main/java/com/example/nuberjam/ui/authentication/AuthActivity.kt
  app/src/main/java/com/example/nuberjam/ui/authentication/AuthViewModel.kt
  app/src/main/java/com/example/nuberjam/ui/authentication/LoginFragment.kt
  app/src/main/java/com/example/nuberjam/ui/authentication/RegisterFragment.kt
  app/src/main/java/com/example/nuberjam/ui/main/MainActivity.kt
  app/src/main/java/com/example/nuberjam/ui/main/adapter/AlbumAdapter.kt
  app/src/main/java/com/example/nuberjam/ui/main/adapter/LibraryAdapter.kt
  app/src/main/java/com/example/nuberjam/ui/main/adapter/MusicAdapter.kt
  app/src/main/java/com/example/nuberjam/ui/main/adapter/PlaylistAdapter.kt
  app/src/main/java/com/example/nuberjam/ui/main/home/HomeFragment.kt
  app/src/main/java/com/example/nuberjam/ui/main/home/HomeViewModel.kt
  app/src/main/java/com/example/nuberjam/ui/main/library/LibraryFragment.kt
  app/src/main/java/com/example/nuberjam/ui/main/library/LibraryViewModel.kt
  app/src/main/java/com/example/nuberjam/ui/main/library/detail/DetailLibraryViewModel.kt
  app/src/main/java/com/example/nuberjam/ui/main/music/MusicViewModel.kt
  app/src/main/java/com/example/nuberjam/ui/main/profile/ProfileFragment.kt
  app/src/main/java/com/example/nuberjam/ui/main/profile/ProfileViewModel.kt
  app/src/main/java/com/example/nuberjam/ui/main/search/SearchViewModel.kt
  app/src/main/java/com/example/nuberjam/utils/Constant.kt
  app/src/main/java/com/example/nuberjam/utils/Event.kt
  app/src/main/java/com/example/nuberjam/utils/FormValidation.kt
  app/src/main/java/com/example/nuberjam/utils/Helper.kt
  app/src/main/java/com/example/nuberjam/utils/Mapping.kt
  app/src/main/res/drawable/bg_gradient.xml
  app/src/main/res/drawable/gif_loading.gif
  app/src/main/res/drawable/ic_navigation_home.xml
  app/src/main/res/drawable/ic_navigation_library.xml
  app/src/main/res/drawable/ic_navigation_profile.xml
  app/src/main/res/drawable/logo_nuberjam_title_rounded.png
  app/src/main/res/drawable/splash_background.xml
  app/src/main/res/layout/activity_auth.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_splash_screen.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_register.xml
  app/src/main/res/layout/linear_loading.xml
  app/src/main/res/layout/password_req_layout.xml
  app/src/main/res/layout/register_appbar.xml
  app/src/main/res/menu/bottom_navigation_menu.xml
  app/src/main/res/navigation/auth_navigation.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: account, feat

#59 refactor(account): MP-281 Add scroll view to login page
  app/src/main/res/layout/fragment_login.xml
Labels: account, refactor

#60 refactor(acount): MP-279 Fix password requirement when no password inserted
  app/src/main/java/com/example/nuberjam/ui/authentication/RegisterFragment.kt
Labels: account, refactor

#61 feat(account) : MP-277 Create Logout Feature & Refactor Login Error
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/nuberjam/data/Repository.kt
  app/src/main/java/com/example/nuberjam/data/source/preferences/AppPreferences.kt
  app/src/main/java/com/example/nuberjam/ui/ViewModelFactory.kt
  app/src/main/java/com/example/nuberjam/ui/authentication/AuthActivity.kt
  app/src/main/java/com/example/nuberjam/ui/authentication/LoginFragment.kt
  app/src/main/java/com/example/nuberjam/ui/main/MainActivity.kt
  app/src/main/java/com/example/nuberjam/ui/main/profile/ProfileFragment.kt
  app/src/main/java/com/example/nuberjam/ui/main/profile/ProfileViewModel.kt
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/navigation/auth_navigation.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: account, feat

#62 feat(account) : MP-273 Auth Feature
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/nuberjam/data/Repository.kt
  app/src/main/java/com/example/nuberjam/data/source/preferences/AppPreferences.kt
  app/src/main/java/com/example/nuberjam/ui/authentication/AuthActivity.kt
  app/src/main/java/com/example/nuberjam/ui/authentication/LoginFragment.kt
  app/src/main/java/com/example/nuberjam/ui/authentication/RegisterFragment.kt
  app/src/main/java/com/example/nuberjam/ui/main/MainActivity.kt
  app/src/main/java/com/example/nuberjam/ui/main/profile/ProfileFragment.kt
  app/src/main/java/com/example/nuberjam/ui/main/profile/ProfileViewModel.kt
  app/src/main/res/anim/slide_in_right.xml
  app/src/main/res/anim/slide_out_left.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/navigation/auth_navigation.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: account, feat

#63 refactor(general) : MP-283 Change Profile Icon Blue
  app/src/main/res/drawable/ic_profile_blue.xml
Labels: general, refactor

#64 refactor(account) : MP-280 Create Logic For Email & Username Case
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/kotlinc.xml
  .idea/misc.xml
  app/src/main/java/com/example/nuberjam/ui/authentication/RegisterFragment.kt
  app/src/main/java/com/example/nuberjam/utils/Constant.kt
Labels: account, refactor

#67 feat(general) : MP-319 Snackbar Event Rotation
  .idea/misc.xml
  app/src/main/java/com/example/nuberjam/ui/authentication/AuthActivity.kt
  app/src/main/java/com/example/nuberjam/ui/authentication/AuthViewModel.kt
  app/src/main/java/com/example/nuberjam/ui/authentication/LoginFragment.kt
  app/src/main/java/com/example/nuberjam/ui/authentication/RegisterFragment.kt
  app/src/main/java/com/example/nuberjam/ui/customview/CustomSnackbar.kt
  app/src/main/java/com/example/nuberjam/ui/main/MainActivity.kt
  app/src/main/java/com/example/nuberjam/ui/main/MainViewModel.kt
  app/src/main/java/com/example/nuberjam/utils/Event.kt
Labels: feat, general

#69 feat(general) : MP-284 Tech Debt Sprint 5
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/kotlinc.xml
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/nuberjam/ui/SplashScreenActivity.kt
  app/src/main/java/com/example/nuberjam/ui/SplashViewModel.kt
  app/src/main/java/com/example/nuberjam/ui/ViewModelFactory.kt
  app/src/main/java/com/example/nuberjam/ui/authentication/AuthActivity.kt
  app/src/main/java/com/example/nuberjam/ui/authentication/AuthViewModel.kt
  app/src/main/java/com/example/nuberjam/ui/authentication/LoginFragment.kt
  app/src/main/java/com/example/nuberjam/ui/authentication/RegisterFragment.kt
  app/src/main/java/com/example/nuberjam/ui/customview/CustomSnackbar.kt
  app/src/main/java/com/example/nuberjam/ui/main/MainActivity.kt
  app/src/main/java/com/example/nuberjam/ui/main/MainViewModel.kt
  app/src/main/java/com/example/nuberjam/ui/main/profile/ProfileFragment.kt
  app/src/main/java/com/example/nuberjam/utils/Constant.kt
  app/src/main/java/com/example/nuberjam/utils/Event.kt
  app/src/main/res/values-night/splash_theme.xml
  app/src/main/res/values/splash_theme.xml
  app/src/main/res/values/themes.xml
Labels: account, feat, general, refactor

#75 feat(general) : MP-294 Create AppBar Home Page
  app/src/main/res/layout/home_appbar.xml
  app/src/main/res/menu/menu_home.xml
  app/src/main/res/values/strings.xml
Labels: feat, general

#76 feat(album + music) : MP-300 Create Shimmer Loading Indicator
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/res/layout/shimmer_album_item.xml
  app/src/main/res/layout/shimmer_home_layout.xml
  app/src/main/res/layout/shimmer_music_item.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
Labels: album, feat, music

#78 feat(general) : MP-298 Create List Music Layout
  app/build.gradle
  app/src/main/res/drawable/ic_add_playlist_gray.xml
  app/src/main/res/drawable/ic_love_gray.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/music_item.xml
  app/src/main/res/values/strings.xml
Labels: feat, general

#79 refactor(account) : MP-327 Blank Error Rotation
  app/src/main/java/com/example/nuberjam/ui/authentication/RegisterFragment.kt
Labels: account, refactor

#80 refactor(general) : MP-329 Snackbar Event Rotation (Login)
  app/src/main/java/com/example/nuberjam/ui/authentication/AuthActivity.kt
  app/src/main/java/com/example/nuberjam/ui/main/MainActivity.kt
Labels: general, refactor

#81 refactor(general) : MP-330 Session error
  app/src/main/java/com/example/nuberjam/ui/authentication/LoginFragment.kt
  app/src/main/java/com/example/nuberjam/ui/main/profile/ProfileFragment.kt
Labels: general, refactor

#82 feat(album): MP-297 Create List Album Layout
  .idea/misc.xml
  app/src/main/res/layout/album_item.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/shimmer_album_item.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: album, feat

#83 refactor(general) : [MP-328] [QA] Tech Debt Sprint 5
  app/src/main/java/com/example/nuberjam/ui/authentication/AuthActivity.kt
  app/src/main/java/com/example/nuberjam/ui/authentication/LoginFragment.kt
  app/src/main/java/com/example/nuberjam/ui/authentication/RegisterFragment.kt
  app/src/main/java/com/example/nuberjam/ui/main/MainActivity.kt
  app/src/main/java/com/example/nuberjam/ui/main/profile/ProfileFragment.kt
Labels: general, refactor, defect

#85 feat(general) : MP-301 Finalized Home Page Layout
  .idea/misc.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/music_item.xml
  app/src/main/res/layout/shimmer_home_layout.xml
  app/src/main/res/layout/shimmer_music_item.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: feat, general

#84 feat(general) : MP-334 Change Apps Icon
  app/src/main/AndroidManifest.xml
Labels: feat, general

#87 feat(general): MP-310 Create showError and showLoading function
  app/src/main/java/com/example/nuberjam/ui/main/home/HomeFragment.kt
  app/src/main/java/com/example/nuberjam/ui/main/home/HomeViewModel.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/shimmer_home_layout.xml
  app/src/main/res/values/dimens.xml
Labels: feat, general

#88 feat(general): MP-303 Wiring AppBar
  app/src/main/java/com/example/nuberjam/ui/main/home/HomeFragment.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/home_appbar.xml
  app/src/main/res/menu/menu_home.xml
Labels: feat, general

#90 feat(music) : MP-314 Create Data Request to List Music
  app/src/main/java/com/example/nuberjam/data/Repository.kt
  app/src/main/java/com/example/nuberjam/data/source/remote/service/ApiService.kt
  app/src/main/java/com/example/nuberjam/utils/Mapping.kt
Labels: feat, music

#91 feat(album) : MP-311 Create Data Request to List Album
  app/src/main/java/com/example/nuberjam/data/Repository.kt
  app/src/main/java/com/example/nuberjam/data/source/remote/service/ApiService.kt
  app/src/main/java/com/example/nuberjam/utils/Mapping.kt
Labels: album, feat
