Repository Nub-en-Nuber/NuberJam-Android, pull requests merged in 2023-07, with the labels that each got.

#1 Create pull_request_template.md
  pull_request_template.md
Labels: docs, general

#2 refactor(general) : MP-191 Code Package Architecture
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/nuberjam/data/Repository.kt
  app/src/main/java/com/example/nuberjam/data/Result.kt
  app/src/main/java/com/example/nuberjam/data/model/Account.kt
  app/src/main/java/com/example/nuberjam/data/model/Album.kt
  app/src/main/java/com/example/nuberjam/data/model/Music.kt
  app/src/main/java/com/example/nuberjam/data/model/Playlist.kt
  app/src/main/java/com/example/nuberjam/data/source/local/entity/RecentFromSearch.kt
  app/src/main/java/com/example/nuberjam/data/source/local/entity/RecentMusicSearch.kt
  app/src/main/java/com/example/nuberjam/data/source/local/service/Dao.kt
  app/src/main/java/com/example/nuberjam/data/source/local/service/Database.kt
  app/src/main/java/com/example/nuberjam/data/source/preference/AppPreference.kt
  app/src/main/java/com/example/nuberjam/data/source/remote/response/DataResponse.kt
  app/src/main/java/com/example/nuberjam/data/source/remote/service/ApiConfig.kt
  app/src/main/java/com/example/nuberjam/data/source/remote/service/ApiService.kt
  app/src/main/java/com/example/nuberjam/di/Injection.kt
  app/src/main/java/com/example/nuberjam/ui/ViewModelFactory.kt
  app/src/main/java/com/example/nuberjam/ui/authentication/AuthViewModel.kt
  app/src/main/java/com/example/nuberjam/ui/main/MainActivity.kt
  app/src/main/java/com/example/nuberjam/ui/main/adapter/AlbumAdapter.kt
  app/src/main/java/com/example/nuberjam/ui/main/adapter/LibraryAdapter.kt
  app/src/main/java/com/example/nuberjam/ui/main/adapter/MusicAdapter.kt
  app/src/main/java/com/example/nuberjam/ui/main/adapter/PlaylistAdapter.kt
  app/src/main/java/com/example/nuberjam/ui/main/home/HomeViewModel.kt
  app/src/main/java/com/example/nuberjam/ui/main/library/LibraryViewModel.kt
  app/src/main/java/com/example/nuberjam/ui/main/library/detail/DetailLibraryViewModel.kt
  app/src/main/java/com/example/nuberjam/ui/main/music/MusicViewModel.kt
  app/src/main/java/com/example/nuberjam/ui/main/profile/ProfileViewModel.kt
  app/src/main/java/com/example/nuberjam/ui/main/search/SearchViewModel.kt
  app/src/main/java/com/example/nuberjam/utils/Event.kt
  app/src/main/java/com/example/nuberjam/utils/Formatter.kt
  app/src/main/java/com/example/nuberjam/utils/Mapping.kt
  app/src/main/res/layout/activity_main.xml
Labels: general, refactor

#3 refactor(general) : MP-198 Add Android Permission and Dependencies
  .idea/.name
  .idea/gradle.xml
  .idea/vcs.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/nuberjam/ui/main/MainActivity.kt
Labels: general, refactor

#6 refactor(general) : MP-199 Create API Result State
  app/src/main/java/com/example/nuberjam/data/Result.kt
Labels: general, refactor

#5 refactor(general) : MP-200 Database Configuration
  app/src/main/java/com/example/nuberjam/data/source/local/entity/RecentFormSearch.kt
  app/src/main/java/com/example/nuberjam/data/source/local/entity/RecentFromSearch.kt
  app/src/main/java/com/example/nuberjam/data/source/local/entity/RecentMusicSearch.kt
  app/src/main/java/com/example/nuberjam/data/source/local/service/Dao.kt
  app/src/main/java/com/example/nuberjam/data/source/local/service/DbConfig.kt
  app/src/main/java/com/example/nuberjam/data/source/local/service/DbDao.kt
Labels: general, refactor

#4 refactor(general) : MP-192 API Configuration
  app/src/main/java/com/example/nuberjam/data/source/remote/response/DataResponse.kt
  app/src/main/java/com/example/nuberjam/data/source/remote/service/ApiConfig.kt
  app/src/main/java/com/example/nuberjam/data/source/remote/service/ApiService.kt
  app/src/main/java/com/example/nuberjam/utils/Constant.kt
Labels: general, refactor

#7 refactor(general) : MP-193 Shared Preferences Configuration
  app/src/main/java/com/example/nuberjam/data/source/preference/AppPreference.kt
  app/src/main/java/com/example/nuberjam/data/source/preference/AppPreferences.kt
Labels: general, refactor

#8 refactor(general) : MP-194 Create ViewModel Configuration
  app/src/main/java/com/example/nuberjam/data/Repository.kt
  app/src/main/java/com/example/nuberjam/di/Injection.kt
  app/src/main/java/com/example/nuberjam/ui/ViewModelFactory.kt
  app/src/main/java/com/example/nuberjam/utils/AppExecutors.kt
Labels: general, refactor

#10 refactor(general) : MP-195 Create Res Configuration
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/themes.xml
Labels: general, refactor

#9 feature(general): MP-196 Add Font to Project, feature(general): MP-197 Create Default Text Style
  app/src/main/res/font/century_gothic.otf
  app/src/main/res/font/century_gothic_bold.otf
  app/src/main/res/font/century_gothic_bold_font.xml
  app/src/main/res/font/century_gothic_bold_italic.otf
  app/src/main/res/font/century_gothic_font.xml
  app/src/main/res/font/century_gothic_italic.otf
  app/src/main/res/values/themes.xml
Labels: feat, general

#11 feat(general): MP-206 Create Build Variant Configuration
  app/build.gradle
Labels: feat, general

#12 feat(general): MP-197 Change Default Text Color
  app/src/main/res/values/themes.xml
Labels: feat, general

#13 refactor(general): MP-1 Change Hello World Text in Main Activity
  app/src/main/res/layout/activity_main.xml
Labels: general, refactor

#15 refactor(general) : MP-228 Change Shared Preference to DataStore
  app/build.gradle
  app/src/main/java/com/example/nuberjam/data/Repository.kt
  app/src/main/java/com/example/nuberjam/data/source/local/service/DbConfig.kt
  app/src/main/java/com/example/nuberjam/data/source/preference/AppPreferences.kt
  app/src/main/java/com/example/nuberjam/data/source/preferences/AppPreferences.kt
  app/src/main/java/com/example/nuberjam/di/Injection.kt
  app/src/main/java/com/example/nuberjam/utils/Constant.kt
Labels: general, refactor

#16 refactor(general) : MP-222 Code Refactoring
  app/build.gradle
  app/src/main/java/com/example/nuberjam/data/Repository.kt
  app/src/main/java/com/example/nuberjam/data/source/local/service/DbConfig.kt
  app/src/main/java/com/example/nuberjam/data/source/preference/AppPreferences.kt
  app/src/main/java/com/example/nuberjam/data/source/preferences/AppPreferences.kt
  app/src/main/java/com/example/nuberjam/data/source/remote/service/ApiConfig.kt
  app/src/main/java/com/example/nuberjam/di/Injection.kt
  app/src/main/java/com/example/nuberjam/utils/AppExecutors.kt
  app/src/main/java/com/example/nuberjam/utils/Constant.kt
Labels: general, refactor

#19 feat(general) : MP-233 Create Button Style
  app/src/main/res/values/themes.xml
Labels: feat, general

#17 feat(account) : MP-235 Login API Connection
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/nuberjam/data/Repository.kt
  app/src/main/java/com/example/nuberjam/data/source/remote/service/ApiService.kt
  app/src/main/java/com/example/nuberjam/utils/Constant.kt
  app/src/main/java/com/example/nuberjam/utils/Formatter.kt
  app/src/main/java/com/example/nuberjam/utils/Helper.kt
Labels: account, feat

#20 feat(general) : MP-231 Snackbar Layout
  app/src/main/res/drawable/sample_baseline_error_outline_24.xml
  app/src/main/res/layout/snackbar.xml
  app/src/main/res/values/themes.xml
Labels: feat, general

#23 feat(general) : MP-251 Add Logo
  app/src/main/res/drawable/logo_nuberjam.png
Labels: general

#22 feat(general) : MP-232 Create Form Style
  app/src/main/res/color/text_color_hint.xml
  app/src/main/res/color/text_input_layout_stroke_color.xml
  app/src/main/res/values/themes.xml
Labels: feat, general

#25 feat(general) : MP-236 Create Logic for Dynamic Custom Snackbar
  app/src/main/java/com/example/nuberjam/ui/customview/CustomSnackbar.kt
  app/src/main/res/drawable/sample_baseline_check_circle_outline_24.xml
  app/src/main/res/layout/snackbar.xml
Labels: feat, general

#24 feat(general) : MP-224 Create Authentication Style
  app/src/main/res/color/text_color_hint.xml
  app/src/main/res/color/text_input_layout_stroke_color.xml
  app/src/main/res/values/themes.xml
Labels: feat, general

#26 feat(general) : MP-223 Snackbar Notification
  app/src/main/java/com/example/nuberjam/ui/customview/CustomSnackbar.kt
  app/src/main/res/drawable/sample_baseline_check_circle_outline_24.xml
  app/src/main/res/drawable/sample_baseline_error_outline_24.xml
  app/src/main/res/layout/snackbar.xml
  app/src/main/res/values/themes.xml
Labels: feat, general

#27 feat(general): MP-259 Add Bottom Navigation Icon
  app/src/main/res/drawable/fluent_library_24_regular.xml
  app/src/main/res/drawable/material_symbols_account_circle_outline.xml
  app/src/main/res/drawable/material_symbols_home_outline.xml
Labels: feat, general

#28 feat(general): MP-212 Create Menu Resource, feat(general): MP-213 Create Blank Fragment
  app/src/main/java/com/example/nuberjam/ui/main/home/HomeFragment.kt
  app/src/main/java/com/example/nuberjam/ui/main/library/LibraryFragment.kt
  app/src/main/java/com/example/nuberjam/ui/main/profile/ProfileFragment.kt
  app/src/main/res/drawable/fluent_library_24_regular.xml
  app/src/main/res/drawable/material_symbols_account_circle_outline.xml
  app/src/main/res/drawable/material_symbols_home_outline.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_library.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/menu/bottom_navigation_menu.xml
  app/src/main/res/values/strings.xml
Labels: feat, general

#30 feat(general): MP-240 Configure MainActivity
  app/src/main/java/com/example/nuberjam/ui/main/MainActivity.kt
Labels: feat, general

#29 feat(general): MP-214 Configure Navigation Component
  app/src/main/java/com/example/nuberjam/ui/main/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/values/dimens.xml
Labels: feat, general

#31 feat(general): MP-211 Main Navigation App
  app/src/main/java/com/example/nuberjam/ui/main/MainActivity.kt
  app/src/main/java/com/example/nuberjam/ui/main/home/HomeFragment.kt
  app/src/main/java/com/example/nuberjam/ui/main/library/LibraryFragment.kt
  app/src/main/java/com/example/nuberjam/ui/main/profile/ProfileFragment.kt
  app/src/main/res/drawable/fluent_library_24_regular.xml
  app/src/main/res/drawable/material_symbols_account_circle_outline.xml
  app/src/main/res/drawable/material_symbols_home_outline.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_library.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/menu/bottom_navigation_menu.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: feat, general

#32 refactor(general): Update PR Template
  pull_request_template.md
Labels: general, refactor

#33 refactor(general) : MP-272 Change Utils Code Structure
  app/src/main/java/com/example/nuberjam/utils/Helper.kt
Labels: general, refactor

#37 feat(general) : MP-260 Add Icons
  app/src/main/java/com/example/nuberjam/ui/customview/CustomSnackbar.kt
  app/src/main/res/drawable/ic_add_playlist_blue.xml
  app/src/main/res/drawable/ic_add_playlist_gray.xml
  app/src/main/res/drawable/ic_back_gray.xml
  app/src/main/res/drawable/ic_camera_blue.xml
  app/src/main/res/drawable/ic_check_circle_white.xml
  app/src/main/res/drawable/ic_checklist_green.xml
  app/src/main/res/drawable/ic_clause_red.xml
  app/src/main/res/drawable/ic_error_circle_white.xml
  app/src/main/res/drawable/ic_forward_gray.xml
  app/src/main/res/drawable/ic_gallery_blue.xml
  app/src/main/res/drawable/ic_gridview_gray.xml
  app/src/main/res/drawable/ic_home_blue.xml
  app/src/main/res/drawable/ic_home_gray.xml
  app/src/main/res/drawable/ic_library_blue.xml
  app/src/main/res/drawable/ic_library_gray.xml
  app/src/main/res/drawable/ic_listview_gray.xml
  app/src/main/res/drawable/ic_love_gray.xml
  app/src/main/res/drawable/ic_love_red.xml
  app/src/main/res/drawable/ic_more_circle_gray.xml
  app/src/main/res/drawable/ic_more_gray.xml
  app/src/main/res/drawable/ic_next_gray.xml
  app/src/main/res/drawable/ic_pause_blue.xml
  app/src/main/res/drawable/ic_pause_gray.xml
  app/src/main/res/drawable/ic_play_blue.xml
  app/src/main/res/drawable/ic_play_gray.xml
  app/src/main/res/drawable/ic_plus_gray.xml
  app/src/main/res/drawable/ic_previous_gray.xml
  app/src/main/res/drawable/ic_profile_blue.xml
  app/src/main/res/drawable/ic_profile_gray.xml
  app/src/main/res/drawable/ic_search_gray.xml
  app/src/main/res/drawable/ic_shuffle_gray.xml
  app/src/main/res/drawable/ic_verified_blue.xml
  app/src/main/res/drawable/logo_nuberjam_notitle_transparent.png
  app/src/main/res/drawable/logo_nuberjam_notitle_white.png
  app/src/main/res/drawable/logo_nuberjam_title_transparent.png
  app/src/main/res/layout/snackbar.xml
  app/src/main/res/raw/gif_loading.json
Labels: feat, general

#38 feat(general) : MP-250 Project Resources
  app/src/main/java/com/example/nuberjam/ui/customview/CustomSnackbar.kt
  app/src/main/res/drawable/ic_add_playlist_blue.xml
  app/src/main/res/drawable/ic_add_playlist_gray.xml
  app/src/main/res/drawable/ic_back_gray.xml
  app/src/main/res/drawable/ic_camera_blue.xml
  app/src/main/res/drawable/ic_check_circle_white.xml
  app/src/main/res/drawable/ic_checklist_green.xml
  app/src/main/res/drawable/ic_clause_red.xml
  app/src/main/res/drawable/ic_error_circle_white.xml
  app/src/main/res/drawable/ic_forward_gray.xml
  app/src/main/res/drawable/ic_gallery_blue.xml
  app/src/main/res/drawable/ic_gridview_gray.xml
  app/src/main/res/drawable/ic_home_blue.xml
  app/src/main/res/drawable/ic_home_gray.xml
  app/src/main/res/drawable/ic_library_blue.xml
  app/src/main/res/drawable/ic_library_gray.xml
  app/src/main/res/drawable/ic_listview_gray.xml
  app/src/main/res/drawable/ic_love_gray.xml
  app/src/main/res/drawable/ic_love_red.xml
  app/src/main/res/drawable/ic_more_circle_gray.xml
  app/src/main/res/drawable/ic_more_gray.xml
  app/src/main/res/drawable/ic_next_gray.xml
  app/src/main/res/drawable/ic_pause_blue.xml
  app/src/main/res/drawable/ic_pause_gray.xml
  app/src/main/res/drawable/ic_play_blue.xml
  app/src/main/res/drawable/ic_play_gray.xml
  app/src/main/res/drawable/ic_plus_gray.xml
  app/src/main/res/drawable/ic_previous_gray.xml
  app/src/main/res/drawable/ic_profile_blue.xml
  app/src/main/res/drawable/ic_profile_gray.xml
  app/src/main/res/drawable/ic_search_gray.xml
  app/src/main/res/drawable/ic_shuffle_gray.xml
  app/src/main/res/drawable/ic_verified_blue.xml
  app/src/main/res/drawable/logo_nuberjam_notitle_transparent.png
  app/src/main/res/drawable/logo_nuberjam_notitle_white.png
  app/src/main/res/drawable/logo_nuberjam_title_transparent.png
  app/src/main/res/layout/snackbar.xml
  app/src/main/res/raw/gif_loading.json
Labels: feat, general

#34 feat(account) : MP-246 Create Logic for Username Case
  app/src/main/java/com/example/nuberjam/data/Repository.kt
  app/src/main/java/com/example/nuberjam/data/source/remote/service/ApiConfig.kt
  app/src/main/java/com/example/nuberjam/data/source/remote/service/ApiService.kt
  app/src/main/java/com/example/nuberjam/utils/FormValidation.kt
Labels: account, feat

#35 feat(account) : MP-247 Create Logic for Email Case
  app/src/main/java/com/example/nuberjam/data/Repository.kt
  app/src/main/java/com/example/nuberjam/utils/FormValidation.kt
Labels: account, feat

#36 feat(account) : MP-245 Create Logic for Password Register Requirement
  app/src/main/java/com/example/nuberjam/utils/FormValidation.kt
Labels: account, feat

#39 feat(account): MP-241 Create Password Requirement Layout
  app/src/main/res/layout/password_req_layout.xml
Labels: account, feat

#40 feat(account): MP-242 Register AppBar Layout
  app/src/main/res/layout/register_appbar.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: account, feat

#41 feat(account): MP-243 Register Page
  app/src/main/java/com/example/nuberjam/ui/authentication/RegisterFragment.kt
  app/src/main/res/drawable/ic_navigation_home.xml
  app/src/main/res/drawable/ic_navigation_library.xml
  app/src/main/res/drawable/ic_navigation_profile.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_register.xml
  app/src/main/res/menu/bottom_navigation_menu.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: account, feat

#42 feat(account): MP-234 Login Page
  app/src/main/java/com/example/nuberjam/ui/authentication/LoginFragment.kt
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: account, feat

#43 feat(account): MP-274 Create Auth Navigation
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/nuberjam/ui/authentication/AuthActivity.kt
  app/src/main/res/layout/activity_auth.xml
  app/src/main/res/navigation/auth_navigation.xml
Labels: account, feat

#44 feat(account): MP-275 Connect Auth Navigation and Main Navigation
  app/src/main/java/com/example/nuberjam/ui/authentication/LoginFragment.kt
  app/src/main/res/navigation/auth_navigation.xml
  app/src/main/res/navigation/main_navigation.xml
Labels: account, feat

#45 feat(account) : MP-237 Wiring Login Data to UI
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/nuberjam/data/Repository.kt
  app/src/main/java/com/example/nuberjam/data/source/remote/service/ApiConfig.kt
  app/src/main/java/com/example/nuberjam/data/source/remote/service/ApiService.kt
  app/src/main/java/com/example/nuberjam/ui/ViewModelFactory.kt
  app/src/main/java/com/example/nuberjam/ui/authentication/AuthActivity.kt
  app/src/main/java/com/example/nuberjam/ui/authentication/AuthViewModel.kt
  app/src/main/java/com/example/nuberjam/ui/authentication/LoginFragment.kt
  app/src/main/java/com/example/nuberjam/ui/authentication/RegisterFragment.kt
  app/src/main/java/com/example/nuberjam/utils/FormValidation.kt
  app/src/main/res/drawable/ic_navigation_home.xml
  app/src/main/res/drawable/ic_navigation_library.xml
  app/src/main/res/drawable/ic_navigation_profile.xml
  app/src/main/res/layout/activity_auth.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_register.xml
  app/src/main/res/layout/linear_loading.xml
  app/src/main/res/layout/password_req_layout.xml
  app/src/main/res/layout/register_appbar.xml
  app/src/main/res/menu/bottom_navigation_menu.xml
  app/src/main/res/navigation/auth_navigation.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: account, feat

#46 feat(account) : MP-238 Form Logic Error
  app/src/main/java/com/example/nuberjam/ui/authentication/LoginFragment.kt
  app/src/main/res/values/strings.xml
Labels: account, feat
