Repository Nub-en-Nuber/NuberJam-Android, pull requests merged in 2023-12, with the labels that each got.

#157 feat(account): 860t23bh9 Create TnC Layout
  app/src/main/res/layout/tnc_appbar.xml
  app/src/main/res/layout/tnc_layout.xml
  app/src/main/res/values/strings.xml
Labels: account, feat

#156 feat(account): 860t23bf6 Create Password Dialog Class
  app/src/main/java/com/example/nuberjam/ui/authentication/RegisterFragment.kt
  app/src/main/java/com/example/nuberjam/ui/main/profile/ProfileFragment.kt
  app/src/main/java/com/example/nuberjam/ui/main/profile/UpdateAccountViewModel.kt
  app/src/main/java/com/example/nuberjam/ui/main/profile/editpassword/EditPasswordDialogFragment.kt
  app/src/main/java/com/example/nuberjam/utils/FormValidation.kt
  app/src/main/java/com/example/nuberjam/utils/extension/GeneralExt.kt
  app/src/main/java/com/example/nuberjam/utils/extension/MappingExt.kt
  app/src/main/res/layout/password_dialog.xml
  app/src/main/res/values/strings.xml
Labels: account, feat

#159 refactor(account): 86cu3dxcj Enhance Profile UI
  app/src/main/java/com/example/nuberjam/ui/main/profile/ProfileFragment.kt
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/values/dimens.xml
Labels: account, refactor

#160 Feat(860t23afq): Terms and Conditions
  app/src/main/java/com/example/nuberjam/ui/main/profile/ProfileFragment.kt
  app/src/main/java/com/example/nuberjam/ui/main/profile/tnc/TncFragment.kt
  app/src/main/res/layout/fragment_tnc.xml
  app/src/main/res/layout/tnc_appbar.xml
  app/src/main/res/layout/tnc_layout.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/values/strings.xml
Labels: account, feat

#162 feat(general) : 860t23d1e Create Error View
  app/src/main/res/drawable/ic_refresh.xml
  app/src/main/res/layout/default_error_state.xml
  app/src/main/res/values/dimens.xml
Labels: feat, general

#163 feat(general): 860t23d19 Create Empty View
  app/src/main/res/layout/default_empty_state.xml
Labels: feat, general

#164 feat(favorite): 860t23cxb Shimmer Loading
  app/src/main/res/layout/shimmer_favorite_layout.xml
Labels: favorite, feat

#166 feat(favorite): 860t23c9t Create Kebab Item Music View
  app/src/main/res/layout/music_kebab_item.xml
Labels: favorite, feat

#165 feat(favorite): 860t23cr1 Configure Read Favorite API
  app/src/main/java/com/example/nuberjam/data/Repository.kt
  app/src/main/java/com/example/nuberjam/data/source/remote/service/ApiService.kt
Labels: favorite, feat

#167 feat(general): 860t23c8w Configure Kenny Multi State View
  app/build.gradle
  app/src/main/java/com/example/nuberjam/data/Result.kt
  app/src/main/java/com/example/nuberjam/ui/main/library/LibraryFragment.kt
  app/src/main/java/com/example/nuberjam/utils/MultiStateViewExt.kt
  app/src/main/java/com/example/nuberjam/utils/ViewExt.kt
  app/src/main/res/layout/default_empty_state.xml
  app/src/main/res/layout/default_error_state.xml
  app/src/main/res/layout/fragment_library.xml
  app/src/main/res/layout/shimmer_favorite_layout.xml
  app/src/main/res/layout/shimmer_library_layout.xml
  app/src/main/res/raw/gif_loading.json
  settings.gradle
Labels: feat, general

#168 refactor(account): #86cu3meyu [APP-DATA] Refactor API Call for Edit Profile
  app/src/main/java/com/example/nuberjam/data/Repository.kt
  app/src/main/java/com/example/nuberjam/data/source/remote/service/ApiService.kt
  app/src/main/java/com/example/nuberjam/utils/extension/MappingExt.kt
Labels: account, refactor

#169 feat(account): #860t239um Create Form Dialog
  app/src/main/java/com/example/nuberjam/data/Repository.kt
  app/src/main/java/com/example/nuberjam/data/source/remote/request/AccountRequest.kt
  app/src/main/java/com/example/nuberjam/data/source/remote/service/ApiService.kt
  app/src/main/java/com/example/nuberjam/ui/authentication/AuthActivity.kt
  app/src/main/java/com/example/nuberjam/ui/authentication/RegisterFragment.kt
  app/src/main/java/com/example/nuberjam/ui/main/profile/ProfileFragment.kt
  app/src/main/java/com/example/nuberjam/ui/main/profile/UpdateAccountViewModel.kt
  app/src/main/java/com/example/nuberjam/ui/main/profile/deleteaccount/DeleteAccountDialogFragment.kt
  app/src/main/java/com/example/nuberjam/ui/main/profile/editname/EditNameDialogFragment.kt
  app/src/main/java/com/example/nuberjam/ui/main/profile/editpassword/EditPasswordDialogFragment.kt
  app/src/main/java/com/example/nuberjam/utils/FormValidation.kt
  app/src/main/java/com/example/nuberjam/utils/extension/GeneralExt.kt
  app/src/main/java/com/example/nuberjam/utils/extension/MappingExt.kt
  app/src/main/res/layout/confirmation_dialog.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/password_dialog.xml
  app/src/main/res/layout/single_form_dialog.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: account, feat

#171 refactor(account): 86cu5961z Change font size Tnc
  app/src/main/res/layout/tnc_layout.xml
Labels: account, refactor

#173 refactor(music): 860t23caa Refactor Music Adapter View Type for each page
  app/src/main/java/com/example/nuberjam/data/Repository.kt
  app/src/main/java/com/example/nuberjam/di/MyModule.kt
  app/src/main/java/com/example/nuberjam/ui/main/adapter/MusicAdapter.kt
  app/src/main/java/com/example/nuberjam/ui/main/home/HomeFragment.kt
  app/src/main/java/com/example/nuberjam/ui/main/library/LibraryFragment.kt
  app/src/main/java/com/example/nuberjam/utils/Constant.kt
  app/src/main/java/com/example/nuberjam/utils/extensions/MultiStateViewExt.kt
  app/src/main/java/com/example/nuberjam/utils/extensions/ViewExt.kt
  app/src/main/java/com/example/nuberjam/utils/network/NetworkConnectionInterceptor.kt
  app/src/main/java/com/example/nuberjam/utils/network/NoConnectivityException.kt
Labels: music, refactor

#172 feat(favorite): 860t23c96 Configure Add Remove Favorite API
  app/src/main/java/com/example/nuberjam/data/Repository.kt
  app/src/main/java/com/example/nuberjam/data/source/remote/request/FavoriteRequest.kt
  app/src/main/java/com/example/nuberjam/data/source/remote/service/ApiService.kt
Labels: favorite, feat

#175 refactor(favorite): 86cu5nvk5 Refactor Loading State in Favorite Icon Button
  app/src/main/res/layout/music_item.xml
  app/src/main/res/layout/music_kebab_item.xml
Labels: favorite, refactor

#176 refactor(general): 86cu595x4 Refactor default value of kenny state
  app/src/main/java/com/example/nuberjam/data/Result.kt
  app/src/main/java/com/example/nuberjam/ui/main/library/LibraryFragment.kt
  app/src/main/java/com/example/nuberjam/utils/extensions/MultiStateViewExt.kt
Labels: bug, general

#174 feat(favorite): 860t23d1v Wiring API data to UI
  app/src/main/java/com/example/nuberjam/data/Repository.kt
  app/src/main/java/com/example/nuberjam/ui/main/library/LibraryFragment.kt
  app/src/main/java/com/example/nuberjam/ui/main/library/detail/DetailLibraryFragment.kt
  app/src/main/java/com/example/nuberjam/ui/main/library/detail/DetailLibraryViewModel.kt
  app/src/main/java/com/example/nuberjam/utils/extensions/GeneralExt.kt
  app/src/main/java/com/example/nuberjam/utils/extensions/MultiStateViewExt.kt
  app/src/main/res/layout/default_empty_state.xml
  app/src/main/res/layout/default_error_state.xml
  app/src/main/res/layout/fragment_detail_library.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/values/strings.xml
Labels: favorite, feat

#177 feat(account): 860t23bk9 Wiring UI, Show Snackbar
  app/src/main/java/com/example/nuberjam/data/Repository.kt
  app/src/main/java/com/example/nuberjam/ui/main/profile/ProfileFragment.kt
  app/src/main/java/com/example/nuberjam/ui/main/profile/editphoto/EditPhotoFragment.kt
  app/src/main/java/com/example/nuberjam/ui/main/profile/editphoto/EditPhotoViewModel.kt
  app/src/main/res/layout/fragment_edit_photo.xml
  app/src/main/res/navigation/main_navigation.xml
Labels: account, feat

#179 feat(account): 860t23afw Photo Fragment
  app/src/main/java/com/example/nuberjam/data/Repository.kt
  app/src/main/java/com/example/nuberjam/ui/main/profile/ProfileFragment.kt
  app/src/main/java/com/example/nuberjam/ui/main/profile/editphoto/EditPhotoFragment.kt
  app/src/main/java/com/example/nuberjam/ui/main/profile/editphoto/EditPhotoViewModel.kt
  app/src/main/res/layout/fragment_edit_photo.xml
  app/src/main/res/navigation/main_navigation.xml
Labels: account, feat

#181 feat(favorite): 860t23cnb Create and apply a Callback Favorite Item Click in Adapter for Each Page
  app/src/main/java/com/example/nuberjam/data/Repository.kt
  app/src/main/java/com/example/nuberjam/data/source/remote/request/FavoriteRequest.kt
  app/src/main/java/com/example/nuberjam/data/source/remote/service/ApiService.kt
  app/src/main/java/com/example/nuberjam/ui/main/adapter/MusicAdapter.kt
  app/src/main/java/com/example/nuberjam/ui/main/home/HomeFragment.kt
  app/src/main/java/com/example/nuberjam/ui/main/home/HomeViewModel.kt
  app/src/main/java/com/example/nuberjam/ui/main/library/detail/DetailLibraryFragment.kt
  app/src/main/java/com/example/nuberjam/ui/main/library/detail/DetailLibraryViewModel.kt
  app/src/main/java/com/example/nuberjam/utils/Mapping.kt
  app/src/main/res/drawable/ic_love_red.xml
  app/src/main/res/layout/favorite_state_button.xml
  app/src/main/res/layout/music_item.xml
  app/src/main/res/layout/music_kebab_item.xml
Labels: favorite, feat

#183 refactor(general): Refactor Fix Develop
  app/src/main/java/com/example/nuberjam/data/Repository.kt
  app/src/main/java/com/example/nuberjam/di/MyModule.kt
  app/src/main/java/com/example/nuberjam/ui/main/profile/editpassword/EditPasswordDialogFragment.kt
  app/src/main/java/com/example/nuberjam/utils/NetworkConnectionInterceptor.kt
  app/src/main/java/com/example/nuberjam/utils/NoConnectivityException.kt
  app/src/main/java/com/example/nuberjam/utils/extension/GeneralExt.kt
  app/src/main/java/com/example/nuberjam/utils/extensions/GeneralExt.kt
  app/src/main/java/com/example/nuberjam/utils/extensions/MappingExt.kt
Labels: general, refactor

#185 feat(general): 86cu5nvnd Configure playlist detail entry point
  app/src/main/java/com/example/nuberjam/ui/main/adapter/AlbumAdapter.kt
  app/src/main/java/com/example/nuberjam/ui/main/adapter/GridPlaylistAdapter.kt
  app/src/main/java/com/example/nuberjam/ui/main/adapter/LinearPlaylistAdapter.kt
  app/src/main/java/com/example/nuberjam/ui/main/home/HomeFragment.kt
  app/src/main/java/com/example/nuberjam/ui/main/library/LibraryFragment.kt
  app/src/main/java/com/example/nuberjam/ui/main/library/detail/DetailLibraryFragment.kt
  app/src/main/java/com/example/nuberjam/ui/main/library/detail/DetailLibraryViewModel.kt
  app/src/main/java/com/example/nuberjam/utils/Constant.kt
  app/src/main/res/navigation/main_navigation.xml
Labels: feat, general

#186 feat(album): 86cu5nvnz Wiring API data to UI
  app/src/main/java/com/example/nuberjam/ui/main/library/detail/DetailLibraryFragment.kt
  app/src/main/java/com/example/nuberjam/ui/main/library/detail/DetailLibraryViewModel.kt
  app/src/main/java/com/example/nuberjam/ui/main/profile/editpassword/EditPasswordDialogFragment.kt
  app/src/main/java/com/example/nuberjam/utils/extensions/GeneralExt.kt
  app/src/main/res/layout/music_item.xml
  app/src/main/res/layout/music_kebab_item.xml
Labels: album, feat

#187 feat(album): 86cu5nvn8 Album Feature
  app/src/main/java/com/example/nuberjam/data/Repository.kt
  app/src/main/java/com/example/nuberjam/data/source/remote/service/ApiService.kt
  app/src/main/java/com/example/nuberjam/ui/main/adapter/AlbumAdapter.kt
  app/src/main/java/com/example/nuberjam/ui/main/adapter/GridPlaylistAdapter.kt
  app/src/main/java/com/example/nuberjam/ui/main/adapter/LinearPlaylistAdapter.kt
  app/src/main/java/com/example/nuberjam/ui/main/home/HomeFragment.kt
  app/src/main/java/com/example/nuberjam/ui/main/library/LibraryFragment.kt
  app/src/main/java/com/example/nuberjam/ui/main/library/detail/DetailLibraryFragment.kt
  app/src/main/java/com/example/nuberjam/ui/main/library/detail/DetailLibraryViewModel.kt
  app/src/main/java/com/example/nuberjam/ui/main/profile/editpassword/EditPasswordDialogFragment.kt
  app/src/main/java/com/example/nuberjam/utils/Constant.kt
  app/src/main/java/com/example/nuberjam/utils/extensions/GeneralExt.kt
  app/src/main/res/layout/music_item.xml
  app/src/main/res/layout/music_kebab_item.xml
  app/src/main/res/navigation/main_navigation.xml
Labels: album, feat
